### ISSUE TITLE
Kijk even naar validatie, rondom duplicate id's

### ISSUE THREAD

**Issue by krijnhoetmer** [RickVellingaa/voorhoede-fdnd-sprint12#19]
Hier gaat iets niet helemaal lekker

https://github.com/RickVellingaa/voorhoede-fdnd-sprint12/blob/3697e8a7d087d41e00a61a7d26cbfd5ef0d8a072/views/index.ejs#L6-L8

**Comment by RickVellingaa** [comment]
Gedaan! Fixed!
