### ISSUE TITLE
Zijn dit nou checkboxen, of radio's?

### ISSUE THREAD

**Issue by krijnhoetmer** [RickVellingaa/voorhoede-fdnd-sprint12#20]
1) Geef het juiste in je HTML weer (`type=radio` vs `type=checkbox`)
2) Pas op met custom styling en afforances; rondjes => radio, vierkantjes => checkbox
3) En volgens mij heb je geen extra JS nodig als je stap 1 goed doet :)

https://github.com/RickVellingaa/voorhoede-fdnd-sprint12/blob/3697e8a7d087d41e00a61a7d26cbfd5ef0d8a072/views/index.ejs#L35-L58

**Comment by RickVellingaa** [comment]
Nu radio's 😜
