### ISSUE TITLE
Moet dit niet search-bar zijn?

### ISSUE THREAD

**Issue by krijnhoetmer** [RickVellingaa/voorhoede-fdnd-sprint12#24]
(Flauw issue, om even te testen hoe dat werkt met een commit message)

https://github.com/RickVellingaa/voorhoede-fdnd-sprint12/blob/c50091b763c69a99a5d51fd86b231d0abfdabd1e/views/index.ejs#L4

**Comment by RickVellingaa** [comment]
Naam aangepast! (closes #24)

**Comment by krijnhoetmer** [comment]
Beetje veel meer dan ik verwacht had, maar nette fix! :P
